### ISSUE TITLE
To Do Management web client is not working anymore

### ISSUE THREAD

**Issue by thesse1** [theNorstroem/todo-management-tool#5]
When I start the web client with `npm run start` or `npm run start:mock`, it will display the following error message:

```
[0] /home/thesse/todo-management-tool/client/node_modules/@web/dev-server-rollup/node_modules/whatwg-url/lib/encoding.js:2
[0] const utf8Encoder = new TextEncoder();
[0]                     ^
[0] 
[0] ReferenceError: TextEncoder is not defined
[0]     at Object.<anonymous> (/home/thesse/todo-management-tool/client/node_modules/@web/dev-server-rollup/node_modules/whatwg-url/lib/encoding.js:2:21)
[0]     at Module._compile (internal/modules/cjs/loader.js:778:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[0]     at Module.load (internal/modules/cjs/loader.js:653:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[0]     at Module.require (internal/modules/cjs/loader.js:692:17)
[0]     at require (internal/modules/cjs/helpers.js:25:18)
[0]     at Object.<anonymous> (/home/thesse/todo-management-tool/client/node_modules/@web/dev-server-rollup/node_modules/whatwg-url/lib/url-state-machine.js:5:34)
[0]     at Module._compile (internal/modules/cjs/loader.js:778:30)
```

This was working fine before commit [9ed624b3afc967af888844378807071c977df9c6](https://github.com/theNorstroem/todo-management-tool/commit/9ed624b3afc967af888844378807071c977df9c6).

**Comment by veith** [comment]
Did you run a `npm install` , after pulling the latest commit?

**Comment by thesse1** [comment]
Yes, I did.
 

Gesendet: Dienstag, 01. Februar 2022 um 09:20 Uhr
Von: "Veith Zäch" ***@***.***>
An: "theNorstroem/todo-management-tool" ***@***.***>
Cc: "Thomas Hesse" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [theNorstroem/todo-management-tool] To Do Management web client is not working anymore (Issue #5)


 

Did you run a npm install , after pulling the latest commit?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by veith** [comment]
I can not reproduce the error. I use node --version => v16.4.2

@thesse1 which node version do you use?

**Comment by veith** [comment]
Your "problem" looks exactly like this one: https://github.com/Automattic/mongoose/issues/10713

**Comment by maltenorstroem** [comment]
@thesse1 
I did a completely fresh install.
`node --version
v17.2.0
npm --version
8.1.4
`
`npm run start:mock`
![Screenshot 2022-02-07 at 11 45 52](https://user-images.githubusercontent.com/9052672/152773475-051c94fd-fe7a-46fe-9b3e-f9c57f8e50ef.png)

It works without any problem. Please provide a repository where I can reproduce the error.
